In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [5]:
corpus=['Thor eating pizza, loki looking pizza',
        'Apple is announcing new iphone tomorrow',
        'Tesla is announcing new model-3 tomorrow',
        'Microsoft is announcing new surface tomorrow',
        'Google is announcing new pixel-6 tomorrow',
        'Amazon is announcing new eco dot tomorrow',
        'I am eating biryani and you are eating grapes',
        'Something is amazing',
       ]

In [27]:
tf=TfidfVectorizer()
transform_output=tf.fit_transform(corpus).toarray()
transform_output

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.3019758 ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.36031943, 0.36031943, 0.        , 0.        , 0.        ,
        0.        , 0.72063885, 0.        , 0.        , 0.        ,
        0.36031943, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.3140158 ,
        0.55947306, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.55947306, 0.27957471,
        0.        , 0.        , 0.        , 0.        , 0.3140158 ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.3140158 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.3140158 ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.27957471,
        0.        , 0.    

In [11]:
print(tf.vocabulary_)

{'thor': 25, 'eating': 9, 'pizza': 21, 'loki': 15, 'looking': 16, 'apple': 5, 'is': 14, 'announcing': 4, 'new': 19, 'iphone': 13, 'tomorrow': 26, 'tesla': 24, 'model': 18, 'microsoft': 17, 'surface': 23, 'google': 11, 'pixel': 20, 'amazon': 2, 'eco': 10, 'dot': 8, 'am': 0, 'biryani': 7, 'and': 3, 'you': 27, 'are': 6, 'grapes': 12, 'something': 22, 'amazing': 1}


In [10]:
tf.idf_

array([2.5040774 , 2.5040774 , 2.5040774 , 2.5040774 , 1.40546511,
       2.5040774 , 2.5040774 , 2.5040774 , 2.5040774 , 2.09861229,
       2.5040774 , 2.5040774 , 2.5040774 , 2.5040774 , 1.25131443,
       2.5040774 , 2.5040774 , 2.5040774 , 2.5040774 , 1.40546511,
       2.5040774 , 2.5040774 , 2.5040774 , 2.5040774 , 2.5040774 ,
       2.5040774 , 1.40546511, 2.5040774 ])

In [12]:
tf.smooth_idf

True

In [13]:
tf.use_idf

True

In [20]:
tf.get_feature_names_out()[11]# giving vocabulary

'google'

In [16]:
all_feature_name=tf.get_feature_names_out()

In [23]:
tf.vocabulary_.get('amazon')

2

# TF-IDF score

In [24]:
for word in all_feature_name:
    indx=tf.vocabulary_.get(word)
    print(f"{word},{tf.idf_[indx]}")

am,2.504077396776274
amazing,2.504077396776274
amazon,2.504077396776274
and,2.504077396776274
announcing,1.4054651081081644
apple,2.504077396776274
are,2.504077396776274
biryani,2.504077396776274
dot,2.504077396776274
eating,2.09861228866811
eco,2.504077396776274
google,2.504077396776274
grapes,2.504077396776274
iphone,2.504077396776274
is,1.251314428280906
loki,2.504077396776274
looking,2.504077396776274
microsoft,2.504077396776274
model,2.504077396776274
new,1.4054651081081644
pixel,2.504077396776274
pizza,2.504077396776274
something,2.504077396776274
surface,2.504077396776274
tesla,2.504077396776274
thor,2.504077396776274
tomorrow,1.4054651081081644
you,2.504077396776274


In [29]:
transform_output[:2]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.3019758 ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.36031943, 0.36031943, 0.        , 0.        , 0.        ,
        0.        , 0.72063885, 0.        , 0.        , 0.        ,
        0.36031943, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.3140158 ,
        0.55947306, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.55947306, 0.27957471,
        0.        , 0.        , 0.        , 0.        , 0.3140158 ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.3140158 , 0.        ]])

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('D:/Data/Ecommerce_data.csv')
print(df.shape)
df.head()

(24000, 2)


Text                   label
0  Urban Ladder Eisner Low Back Study-Office Comp...               Household
1  Contrast living Wooden Decorative Box,Painted ...               Household
2  IO Crest SY-PCI40010 PCI RAID Host Controller ...             Electronics
3  ISAKAA Baby Socks from Just Born to 8 Years- P...  Clothing & Accessories
4  Indira Designer Women's Art Mysore Silk Saree ...  Clothing & Accessories

In [3]:
df.label.value_counts()

Household                 6000
Electronics               6000
Clothing & Accessories    6000
Books                     6000
Name: label, dtype: int64

In [4]:
df['label_num']=df.label.map({
    'Household': 0,
    'Books': 1,
    'Electronics': 2,
    'Clothing & Accessories': 3
})

In [5]:
df.head()

Text                   label  \
0  Urban Ladder Eisner Low Back Study-Office Comp...               Household   
1  Contrast living Wooden Decorative Box,Painted ...               Household   
2  IO Crest SY-PCI40010 PCI RAID Host Controller ...             Electronics   
3  ISAKAA Baby Socks from Just Born to 8 Years- P...  Clothing & Accessories   
4  Indira Designer Women's Art Mysore Silk Saree ...  Clothing & Accessories   

   label_num  
0          0  
1          0  
2          2  
3          3  
4          3

In [6]:
from sklearn.model_selection import train_test_split

In [17]:
X_train,X_test,y_train,y_test=train_test_split(
df.Text,df.label_num,test_size=0.2,random_state=2022,stratify=df.label_num)

In [18]:
print("Shape of X_train :",X_train.shape)
print("Shape of X_test: ",X_test.shape)

Shape of X_train : (19200,)
Shape of X_test:  (4800,)


In [19]:
y_train.value_counts()

0    4800
2    4800
3    4800
1    4800
Name: label_num, dtype: int64

In [20]:
y_test.value_counts()

0    1200
2    1200
3    1200
1    1200
Name: label_num, dtype: int64

In [32]:
X_train[15820]

"IRIS Furniture Children Deluxe Spiderman Toddler Bed with Attached guardrails Toddler Bed from IRIS Make dreams come true with beds featuring their favourite characters. Your child will love this bed that features his or her favourite characters on the headboard and footboard. A sturdy plastic and steel frame with toddler guardrails on both sides will help ensure that your little one stays safely in bed. A Bed with Style This bed evokes the characters and stories kids love to dream about. Colourful graphics on the headboard and footboard help spark your child's imagination. Sweet Dreams Cozy and just-their-size, this toddler bed will create a space they love spending time in. Climb Right In The bed is low to the ground to help make it easy for your little one to get into and out of Stay Safe Two attached toddler guardrails keep your child tucked in safely throughout the night and help your little one transition from a crib to a toddler-size bed."

In [36]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

In [50]:
clf= Pipeline([
    ('vectorizer_ifidf',TfidfVectorizer()),
    ('KNN',KNeighborsClassifier())
])

In [53]:
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.96      0.95      1200
           1       0.97      0.95      0.96      1200
           2       0.97      0.97      0.97      1200
           3       0.97      0.98      0.97      1200

    accuracy                           0.96      4800
   macro avg       0.96      0.96      0.96      4800
weighted avg       0.96      0.96      0.96      4800

