In [69]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [2]:
df=pd.read_csv('D:\Data\spam.csv')

In [3]:
df.head(5)

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Message[2]

"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

In [5]:
df.describe()

Category                 Message
count      5572                    5572
unique        2                    5157
top         ham  Sorry, I'll call later
freq       4825                      30

In [6]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

# Create column using Category column and give value 0,1

In [7]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [8]:
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [9]:
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)

In [10]:
X_train.shape

(4457,)

In [11]:
y_train.shape

(4457,)

In [12]:
X_test.shape

(1115,)

In [13]:
y_test.shape

(1115,)

In [14]:
type(X_train)

pandas.core.series.Series

In [15]:
X_train[:4]

466     great princess! I love giving and receiving or...
3782    Dear friends, sorry for the late information. ...
4848    I am in escape theatre now. . Going to watch K...
5383    Good day to You too.Pray for me.Remove the tee...
Name: Message, dtype: object

In [16]:
X_train[:4]

466     great princess! I love giving and receiving or...
3782    Dear friends, sorry for the late information. ...
4848    I am in escape theatre now. . Going to watch K...
5383    Good day to You too.Pray for me.Remove the tee...
Name: Message, dtype: object

In [17]:
type(y_train)

pandas.core.series.Series

In [18]:
y_train[:100]

466     0
3782    0
4848    0
5383    0
1987    0
       ..
440     0
3668    0
5282    0
1841    0
459     0
Name: spam, Length: 100, dtype: int64

# Apply Algorithm

In [19]:
cv=CountVectorizer()

# Convert pandas series to array

In [21]:
X_train.values

array(['great princess! I love giving and receiving oral. Doggy style is my fave position. How about you? I enjoy making love  &lt;#&gt;  times per night :)',
       'Dear friends, sorry for the late information. Today is the birthday of our loving Ar.Praveesh. for more details log on to face book and see. Its his number + &lt;#&gt; . Dont miss a delicious treat.',
       'I am in escape theatre now. . Going to watch KAVALAN in a few minutes',
       ...,
       'You are everywhere dirt, on the floor, the windows, even on my shirt. And sometimes when i open my mouth, you are all that comes flowing out. I dream of my world without you, then half my chores are out too. A time of joy for me, lots of tv shows i.ll see. But i guess like all things you just must exist, like rain, hail and mist, and when my time here is done, you and i become one.',
       "It's not that you make me cry. It's just that when all our stuff happens on top of everything else, it pushes me over the edge. You don't

In [23]:
X_train_cv=cv.fit_transform(X_train.values)

In [28]:
X_train_cv.toarray()[2]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [29]:
X_train_cv.shape

(4457, 7776)

In [30]:
cv.vocabulary_

{'great': 3244,
 'princess': 5409,
 'love': 4228,
 'giving': 3157,
 'and': 962,
 'receiving': 5632,
 'oral': 4962,
 'doggy': 2400,
 'style': 6567,
 'is': 3751,
 'my': 4659,
 'fave': 2795,
 'position': 5321,
 'how': 3530,
 'about': 753,
 'you': 7740,
 'enjoy': 2605,
 'making': 4330,
 'lt': 4250,
 'gt': 3270,
 'times': 6926,
 'per': 5135,
 'night': 4764,
 'dear': 2194,
 'friends': 3013,
 'sorry': 6339,
 'for': 2947,
 'the': 6835,
 'late': 4026,
 'information': 3680,
 'today': 6964,
 'birthday': 1362,
 'of': 4881,
 'our': 4991,
 'loving': 4238,
 'ar': 1047,
 'praveesh': 5364,
 'more': 4580,
 'details': 2279,
 'log': 4179,
 'on': 4923,
 'to': 6957,
 'face': 2744,
 'book': 1420,
 'see': 5985,
 'its': 3769,
 'his': 3448,
 'number': 4844,
 'dont': 2417,
 'miss': 4508,
 'delicious': 2239,
 'treat': 7057,
 'am': 932,
 'in': 3646,
 'escape': 2642,
 'theatre': 6838,
 'now': 4830,
 'going': 3184,
 'watch': 7427,
 'kavalan': 3906,
 'few': 2825,
 'minutes': 4500,
 'good': 3196,
 'day': 2181,
 'too':

In [39]:
cv.get_feature_names_out()[6869]

'thinking'

In [40]:
X_train_np=X_train_cv.toarray()

In [44]:
X_train_np[:4][1]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [45]:
np.where(X_train_np[0]!=0)

(array([ 753,  962, 2400, 2605, 2795, 3157, 3244, 3270, 3530, 3751, 4228,
        4250, 4330, 4659, 4764, 4962, 5135, 5321, 5409, 5632, 6567, 6926,
        7740], dtype=int64),)

In [55]:
X_train[:4][466]

'great princess! I love giving and receiving oral. Doggy style is my fave position. How about you? I enjoy making love  &lt;#&gt;  times per night :)'

In [60]:
X_train_np[0][753]

1

In [64]:
cv.get_feature_names_out()[6567]

'style'

# Build machine learning module

In [67]:
model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [68]:
X_test_cv=cv.transform(X_test)

In [70]:
y_predict=model.predict(X_test_cv)

In [72]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       972
           1       0.99      0.93      0.96       143

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.98      1115
weighted avg       0.99      0.99      0.99      1115



# Test the model

In [93]:
emails=[
    'Hi sajan how are you?',
    'upto 50% discoutn on parking',
    'how can i help you',
    'sorry i can not '
    "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"
]

In [94]:
emails

['Hi sajan how are you?',
 'upto 50% discoutn on parking',
 'how can i help you',
 "sorry i can not Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"]

In [95]:
email_count=cv.transform(emails)

In [96]:
model.predict(email_count)

array([0, 1, 0, 1], dtype=int64)