In [ ]:
#<<<<<<<<<<<<<<<<<<<<<<Text Representation>>>>>>>>>>>>>>>>>>>>>>>>>>

# Using bag of word(bow)

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

In [2]:
df=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [3]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [4]:
cv=CountVectorizer()

In [5]:
bow=cv.fit_transform(df['text'])

# Print vocabbulary

In [6]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [7]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]
[[0 1 1 0 1]]
[[1 1 0 0 1]]


In [8]:
cv.transform(["campusx watch and write comment of campusx"]).toarray()

array([[2, 1, 0, 1, 1]], dtype=int64)

# N-gram, By-gram, Uni-gram,Tri-gram or(Bag of n-gram)

# Using By_gram

In [11]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [12]:
cv_by=CountVectorizer(ngram_range=(2,2))

In [13]:
transform_word=cv_by.fit_transform(df['text'])

In [14]:
print(cv_by.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [15]:
print(transform_word[0].toarray())
print(transform_word[1].toarray())
print(transform_word[2].toarray())
print(transform_word[3].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]
[[0 1 0 0 0 1]]


# If we give (1,2) in hyper parameter than print both uni-gram and By-gram

In [4]:
CV=CountVectorizer(ngram_range=(1,2))

In [18]:
bow1=CV.fit_transform(df['text'])

In [19]:
print(CV.vocabulary_) #5+6=11

{'people': 4, 'watch': 7, 'campusx': 0, 'people watch': 5, 'watch campusx': 8, 'campusx watch': 1, 'write': 9, 'comment': 3, 'people write': 6, 'write comment': 10, 'campusx write': 2}


In [20]:
print(bow1[0].toarray())
print(bow1[1].toarray())

[[1 0 0 0 1 1 0 1 1 0 0]]
[[2 1 0 0 0 0 0 1 1 0 0]]


# Using Tri_gram

In [22]:
Cv=CountVectorizer(ngram_range=(3,3))

In [23]:
bow2=Cv.fit_transform(df['text'])

In [24]:
print(Cv.vocabulary_)

{'people watch campusx': 2, 'campusx watch campusx': 0, 'people write comment': 3, 'campusx write comment': 1}


In [25]:
print(bow2[0].toarray())
print(bow2[1].toarray())

[[0 0 1 0]]
[[1 0 0 0]]


# Text representation using term frequency and inverse document frequency (TF-IDF)

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()

In [36]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [38]:
tf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [40]:
tf.idf_

array([1.22314355, 1.51082562, 1.51082562, 1.51082562, 1.51082562])

In [41]:
tf.get_feature_names_out()

array(['campusx', 'comment', 'people', 'watch', 'write'], dtype=object)